name: Scrape FBref match shooting

on:
  schedule:
    - cron: "45 17 * 1-5,8-12 0,2,4"
  workflow_dispatch:

jobs:
  update-fb-match-shooting:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Package Installation
        run: Rscript -e 'install.packages(c("devtools", "dplyr", "purrr", "tidyr", "tibble", "lubridate", "readr", "piggyback"))'
      - name: worldfootballR Package Installation
        run: Rscript -e 'devtools::install_github("JaseZiv/worldfootballR")'
      - name: Update match results
        run: Rscript -e 'source(file.path("R", "fb_match_shooting", "update_fb_match_shooting.R"), echo = TRUE)'
