name: Scrape FBref match summaries

on:
  schedule:
    - cron: "58 17 * 1-5,8-12 0,2,4"
    workflow_dispatch:
    
jobs:
  update-fb-advanced-match-stats:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Package Installation
        run: Rscript -e 'install.packages(c("remotes", "dplyr", "purrr", "tidyr", "tibble", "readr", "piggyback"))'
      - name: worldfootballR Package Installation
        run: Rscript -e 'remotes::install_github("JaseZiv/worldfootballR")'
      - name: Update match stats
        run: Rscript -e 'source(file.path("R", "fb_match_summary", "update_fb_match_summary.R"), echo = TRUE)'
