name: Scrape fotmob matches by date

# At 23:01 everyday.
on:
  schedule:
    - cron: "1 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-match-results:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    # retrieve token
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Package Installation
        run: Rscript -e 'install.packages(c("dplyr", "devtools", "purrr", "tidyr", "lubridate", "janitor"))'
      - name: worldfootballR Package Installation
        run: Rscript -e 'devtools::install_github("JaseZiv/worldfootballR")'
      - name: Update match results
        run: Rscript -e 'source(file.path("R", "fotmob_matches_by_date", "update_fotmob_matches_by_date.R"), echo = TRUE)'
      - name: Commit
        run: |
          git config --global user.name 'JaseZiv'
          git config --global user.email 'jaseziv83@gmail.com'
          git add .
          git commit -m 'updating data' || echo "No changes to commit"
          git push || echo "No changes to commit"
