name: Scrape FBref match shooting

# At 23:31 daily.
on:
  schedule:
    - cron: "55 23 * * *"

jobs:
  update-fb-match-shooting:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Package Installation
        run: Rscript -e 'install.packages(c("devtools", "dplyr", "purrr", "tidyr", "tibble", "readr", "piggyback"))'
      - name: worldfootballR Package Installation
        run: Rscript -e 'devtools::install_github("JaseZiv/worldfootballR")'
      - name: Update match results
        run: Rscript -e 'source(file.path("R", "fb_match_shooting", "update_fb_match_shooting.R"), echo = TRUE)'
      - name: Commit
        run: |
          git config --global user.name 'JaseZiv'
          git config --global user.email 'jaseziv83@gmail.com'
          git add .
          git commit -m 'updating fotmob match details' || echo "No changes to commit"
          git push || echo "No changes to commit"
